from django.db import models
from datetime import datetime 

# Create your models here.


"""
    create table Student(
        id serial not null primary key,
        first_name varchar(50) not null,
        last_name varchar(50) not null,
        date_of_birth date not null,
        place_of_birth varchar(255) not null,
        residence varchar(255) not null,
        father_name varchar(100) not null,
        mother_name varchar(100) not null,
        guardian_name varchar(100) not null,
        grade int not null,
        section varchar(2) not null,
        gender varchar(10) not null
    );

    - 12 fields, 11 in the model, since ID is generated by postgres sequentially
"""
class Student(models.Model):
    first_name = models.CharField(max_length=50, null=False)
    last_name  = models.CharField(max_length=50, null=False)
    date_of_birth = models.DateField()
    place_of_birth = models.CharField(max_length=255, null=False)
    residence = models.CharField(max_length=255, null=False)
    gender = models.CharField(max_lenght=10, null=False)
    father_name = models.CharField(max_length=100, null=False)
    mother_name = models.CharField(max_length=100, null=False)
    grade = models.IntegerField(null=False)
    section = models.CharField(max_length=2, null=False)

